// Seed data lifted from the Claude Design hand-off. Used by:
//   - the web app's mock client during stub-mode development,
//   - the bridge's parser tests (synthetic fixtures),
//   - integration tests that need a deterministic snapshot.

import type {
  AlarmMessage,
  DailyProgram,
  Device,
  Room,
  SystemState,
  WeeklyProgram,
} from "./index.js";

const NOW = Date.now();
const ago = (sec: number): string => new Date(NOW - sec * 1000).toISOString();

export const seedRooms: Room[] = [
  {
    id: "r-arianna",
    zone: 0,
    name: "Arianna",
    temperature: 22.5,
    humidity: 47,
    setpointHeating: 20.0,
    setpointCooling: 24.0,
    setpointNormal: 20.0,
    setpointReduced: 18.5,
    setpointStandby: 23.0,
    mode: "standby",
    programOverride: false,
    hasFan: false,
    hasFlap: false,
    hasLight: false,
    fan: 0,
    flap: 0,
    light: false,
    fanRunning: false,
    calibrationTemp: 0.0,
    calibrationHumidity: 0,
    programDailyId: 1,
    programWeeklyId: 1,
    lock: false,
    autoStart: true,
    windowDetection: true,
    floor: "Piano 1",
    meta: { lastUpdatedAt: ago(4) },
  },
  {
    id: "r-manu",
    zone: 1,
    name: "Manu",
    temperature: 23.8,
    humidity: 47,
    setpointHeating: 20.0,
    setpointCooling: 24.0,
    setpointNormal: 20.0,
    setpointReduced: 18.5,
    setpointStandby: 23.0,
    mode: "standby",
    programOverride: false,
    hasFan: false,
    hasFlap: false,
    hasLight: false,
    fan: 0,
    flap: 0,
    light: false,
    fanRunning: false,
    calibrationTemp: 0.0,
    calibrationHumidity: 0,
    programDailyId: 1,
    programWeeklyId: 1,
    lock: false,
    autoStart: true,
    windowDetection: true,
    floor: "Piano 1",
    meta: { lastUpdatedAt: ago(6) },
  },
  {
    id: "r-cucina",
    zone: 2,
    name: "Cucina",
    temperature: 24.7,
    humidity: 47,
    setpointHeating: 20.0,
    setpointCooling: 24.0,
    setpointNormal: 20.0,
    setpointReduced: 18.5,
    setpointStandby: 23.0,
    mode: "standby",
    programOverride: false,
    hasFan: false,
    hasFlap: false,
    hasLight: false,
    fan: 0,
    flap: 0,
    light: false,
    fanRunning: false,
    calibrationTemp: -0.2,
    calibrationHumidity: 0,
    programDailyId: 1,
    programWeeklyId: 1,
    lock: false,
    autoStart: true,
    windowDetection: true,
    floor: "Piano Terra",
    meta: { lastUpdatedAt: ago(2) },
  },
  {
    id: "r-salone",
    zone: 3,
    name: "Salone",
    temperature: 21.7,
    humidity: 47,
    setpointHeating: 20.0,
    setpointCooling: 24.0,
    setpointNormal: 20.0,
    setpointReduced: 18.5,
    setpointStandby: 23.0,
    mode: "program",
    programOverride: false,
    hasFan: false,
    hasFlap: false,
    hasLight: false,
    fan: 0,
    flap: 0,
    light: false,
    fanRunning: false,
    calibrationTemp: 0.1,
    calibrationHumidity: -1,
    programDailyId: 1,
    programWeeklyId: 1,
    lock: false,
    autoStart: true,
    windowDetection: true,
    floor: "Piano Terra",
    meta: { lastUpdatedAt: ago(12) },
  },
];

export const seedSystem: SystemState = {
  installationName: "Casa",
  operatingMode: "manual_heating",
  energyLevel: "standby",
  outdoorTemp: 19.0,
  outdoorOffset: 0,
  seasonStart: "10-15",
  seasonEnd: "04-30",
  reachable: true,
  fw: {
    master: "6.15",
    web: "0.25",
    umodules: { umodule0: "1.2" },
  },
  uniqueCode: "aabbccdd00112233445566778899aabbccddeeff00112233",
  ssid: "manu-iot",
  meta: { lastUpdatedAt: ago(3) },
};

export const seedAlarms: AlarmMessage[] = [
  {
    id: "a-1",
    severity: "warning",
    source: "MC 1",
    code: "2/02/06/06/01/051/3",
    title: "Curva mista oltre soglia",
    detail: "Temperatura mandata superiore al setpoint per >5 min.",
    startedAt: ago(60 * 18),
    resolvedAt: null,
  },
  {
    id: "a-2",
    severity: "info",
    source: "Base",
    code: "1/00/01/00/00/002/1",
    title: "Riavvio pianificato",
    detail: "Aggiornamento FW Master 6.14 → 6.15.",
    startedAt: ago(60 * 60 * 6),
    resolvedAt: ago(60 * 60 * 6 - 120),
  },
  {
    id: "a-3",
    severity: "error",
    source: "Salone",
    code: "3/04/02/01/00/103/2",
    title: "Sensore umidità fuori range",
    detail: "Lettura 110 % – calibrazione richiesta.",
    startedAt: ago(60 * 60 * 26),
    resolvedAt: ago(60 * 60 * 25),
  },
  {
    id: "a-4",
    severity: "warning",
    source: "U-Modul 1",
    code: "2/01/03/02/00/021/1",
    title: "Comunicazione intermittente",
    detail: "3 pacchetti persi su MC1 in 1 min.",
    startedAt: ago(60 * 60 * 48),
    resolvedAt: ago(60 * 60 * 47),
  },
  {
    id: "a-5",
    severity: "info",
    source: "System",
    code: "1/00/02/00/00/004/1",
    title: "Cambio stagione",
    detail: "Passaggio automatico estate → inverno.",
    startedAt: ago(60 * 60 * 24 * 7),
    resolvedAt: ago(60 * 60 * 24 * 7 - 60),
  },
  {
    id: "a-6",
    severity: "warning",
    source: "Cucina",
    code: "2/02/06/06/01/044/2",
    title: "Setpoint non raggiunto",
    detail: "Δ > 2 °C dopo 120 min di richiesta.",
    startedAt: ago(60 * 60 * 24 * 9),
    resolvedAt: ago(60 * 60 * 24 * 9 - 800),
  },
  {
    id: "a-7",
    severity: "critical",
    source: "Base",
    code: "4/00/00/01/00/200/3",
    title: "Caldaia non risponde",
    detail: "Nessun ack su richiesta calore.",
    startedAt: ago(60 * 60 * 24 * 14),
    resolvedAt: ago(60 * 60 * 24 * 14 - 1800),
  },
  {
    id: "a-8",
    severity: "info",
    source: "System",
    code: "1/00/01/00/00/001/1",
    title: "Avvio sistema",
    detail: "Boot completato in 38 s.",
    startedAt: ago(60 * 60 * 24 * 30),
    resolvedAt: ago(60 * 60 * 24 * 30 - 40),
  },
];

const buildDaily = (pattern: number[]): number[] => {
  const bits = new Array(96).fill(0);
  for (let i = 0; i < pattern.length; i += 2) {
    const start = pattern[i]!;
    const end = pattern[i + 1]!;
    for (let q = start; q < end; q++) bits[q] = 1;
  }
  return bits;
};

// Names match the REHAU device — there are no custom labels, just indexes.
export const seedDailyPrograms: DailyProgram[] = [
  { id: 1,  name: "", bits: buildDaily([24, 36, 68, 92]) },
  { id: 2,  name: "", bits: buildDaily([32, 96]) },
  { id: 3,  name: "", bits: buildDaily([24, 92]) },
  { id: 4,  name: "", bits: buildDaily([0, 96]) },
  { id: 5,  name: "", bits: buildDaily([0, 28, 84, 96]) },
  { id: 6,  name: "", bits: buildDaily([20, 44]) },
  { id: 7,  name: "", bits: buildDaily([48, 76]) },
  { id: 8,  name: "", bits: buildDaily([72, 92]) },
  { id: 9,  name: "", bits: buildDaily([28, 40, 64, 88]) },
  { id: 10, name: "", bits: buildDaily([24, 32, 56, 92]) },
];

export const seedWeeklyPrograms: WeeklyProgram[] = [
  { id: 1, name: "", days: [1, 1, 1, 1, 1, 2, 2] },
  { id: 2, name: "", days: [3, 3, 3, 3, 3, 2, 2] },
  { id: 3, name: "", days: [4, 4, 4, 4, 4, 4, 4] },
  { id: 4, name: "", days: [5, 5, 5, 5, 5, 5, 5] },
  { id: 5, name: "", days: [1, 9, 1, 9, 1, 2, 2] },
];

export const seedDevices: Device[] = [
  { id: "base-1", kind: "base", name: "Base 1", fwVersion: "6.15", online: true, uptime: 412 },
  { id: "umod-1", kind: "u-module", name: "U-Modul 1", fwVersion: "6.15", online: true, uptime: 412 },
  { id: "mc-1", kind: "mixed-circuit", name: "Circuito misto 1", fwVersion: "0.25", online: true, uptime: 410 },
  { id: "th-arianna", kind: "thermostat", name: "Termostato Arianna", fwVersion: "6.15", online: true, uptime: 412 },
  { id: "th-manu", kind: "thermostat", name: "Termostato Manu", fwVersion: "6.15", online: true, uptime: 412 },
  { id: "th-cucina", kind: "thermostat", name: "Termostato Cucina", fwVersion: "6.15", online: true, uptime: 411 },
  { id: "th-salone", kind: "thermostat", name: "Termostato Salone", fwVersion: "6.15", online: true, uptime: 412 },
];

/** Partial translation of known REHAU fault codes — extend over time. */
export const alarmCodeLookup: Record<string, string> = {
  "2/02/06/06/01/051/3": "Curva mista oltre soglia di mandata",
  "1/00/01/00/00/002/1": "Riavvio pianificato dopo aggiornamento FW",
  "3/04/02/01/00/103/2": "Sensore umidità ambiente fuori range",
  "2/01/03/02/00/021/1": "Comunicazione bus intermittente",
  "1/00/02/00/00/004/1": "Cambio automatico di stagione",
  "2/02/06/06/01/044/2": "Setpoint non raggiunto entro tempo limite",
  "4/00/00/01/00/200/3": "Caldaia non risponde alle richieste",
  "1/00/01/00/00/001/1": "Avvio sistema completato",
};
